# Generated by Django 3.1 on 2020-09-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_type',
            field=models.TextField(null=True, verbose_name='тип поля свободного ответа (текст/число)'),
        ),
    ]
