version: '3.8'

networks:
  traefik_proxy:
    external: true
  internal:
    external: false

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - static_volume:/usr/src/app/
    expose:
      - 8080
    env_file:
      - ./.env.dev
    networks:
      - internal
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static/
    depends_on:
      - web
    ports:
      - 80:80
    networks:
      - traefik_proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`statedu.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls.certresolver=letsEncrypt"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"


volumes:
  postgres_data:
  static_volume:
