# Generated by Django 3.1 on 2020-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='block_type',
            field=models.IntegerField(null=True, verbose_name='тип блока вопросов (обычные или таблица с возможностью добавления)'),
        ),
    ]
