# Generated by Django 3.1 on 2020-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_questionblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_mask',
            field=models.TextField(null=True, verbose_name='маска ввода'),
        ),
    ]
