# Generated by Django 3.1 on 2020-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_question_field_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_placeholder',
            field=models.TextField(null=True, verbose_name='подпись к полю'),
        ),
    ]
