# Generated by Django 3.1 on 2020-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_question_field_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='essance_label',
            field=models.TextField(null=True, verbose_name='кого (что) добавляем'),
        ),
    ]
