# Generated by Django 3.1 on 2020-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_questionblock_essance_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respid', models.CharField(max_length=100, verbose_name='уникальный код респондента')),
                ('datapost', models.TextField(null=True, verbose_name='исходник данных')),
                ('result_date', models.DateTimeField(verbose_name='дата заполнения')),
            ],
        ),
    ]
