# Generated by Django 3.1 on 2020-09-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.CharField(max_length=100, verbose_name='уникальный код респондента')),
                ('status', models.IntegerField(verbose_name='статус анкеты')),
                ('respondent_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graduates.respondent')),
            ],
        ),
    ]
