# Generated by Django 3.1 on 2020-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0007_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_required',
            field=models.IntegerField(null=True, verbose_name='обязательность заполнения (0-нет, 1-да)'),
        ),
    ]
