# Generated by Django 3.1 on 2020-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0008_question_field_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_clarification',
            field=models.TextField(null=True, verbose_name='пояснение к вопросу'),
        ),
    ]
