# Generated by Django 3.1 on 2020-08-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_number', models.IntegerField(verbose_name='номер ответа')),
                ('answer_name', models.TextField(verbose_name='ответ')),
                ('answer_type', models.IntegerField(verbose_name='тип ответа')),
                ('answer_catalog', models.CharField(max_length=50, verbose_name='название таблицы БД для формирования поля со списком')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='номер вопроса')),
                ('question_name', models.TextField(verbose_name='вопрос')),
                ('question_type', models.IntegerField(verbose_name='тип вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_type', models.IntegerField(verbose_name='тип респондента')),
                ('respondent_name', models.CharField(max_length=100, verbose_name='название типа респондента')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.IntegerField(verbose_name='уникальный номер респондента')),
                ('result_free', models.TextField(verbose_name='свободный ответ')),
                ('result_date', models.DateField(verbose_name='дата заполнения')),
                ('answer_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.answer')),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.question')),
                ('respondent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.respondent')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='respondent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.respondent'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='respondent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.respondent'),
        ),
    ]
