# Generated by Django 3.1 on 2020-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_free',
            field=models.TextField(null=True, verbose_name='свободный ответ'),
        ),
    ]
