# Generated by Django 3.1 on 2020-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_auto_20200828_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_catalog',
            field=models.CharField(max_length=50, null=True, verbose_name='название таблицы БД для формирования поля со списком'),
        ),
    ]
