# Generated by Django 3.1 on 2020-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_auto_20200831_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='answer_number',
        ),
        migrations.AddField(
            model_name='result',
            name='result_result',
            field=models.IntegerField(null=True, verbose_name='ответ'),
        ),
    ]
