# Generated by Django 3.1 on 2020-09-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_auto_20200902_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_catalog',
        ),
    ]
